### PR TITLE
Add a Simple RCLL Demo Agent

### PR DESCRIPTION
**Pull request by snoato**
Add a basic agent skeleton to the ROS2 CX that can be built upon to build a minimal example for all the integrations necessary to develop an agent for the RCLL with the ROS2 CX

### CODE REVIEW

**Review by TarikViehmann — COMMENTED** [review]
Why is the proto directory inside the launch dir? Wouldn't it make more sense to have it on top level?

**Comment by snoato** [comment]
> Why is the proto directory inside the launch dir? Wouldn't it make more sense to have it on top level?

I thought it makes sense to put it with the launch files as it would be different for every project and we view these launch files more as examples right? What exactly do you mean by top level? the topmost level of this project?

**Comment by TarikViehmann** [comment]
Toplevel of the package, these are not launch files so i do not expect them to be in the launch dir.
The whole bringup package is an example, launch files, params, etc simply show how to utilize the common packages.

Hence i suggest to simply have a proto dir within cx_bringup.

**Comment by snoato** [comment]
> Toplevel of the package, these are not launch files so i do not expect them to be in the launch dir. The whole bringup package is an example, launch files, params, etc simply show how to utilize the common packages.
> 
> Hence i suggest to simply have a proto dir within cx_bringup.

Makes sense, will take care of it!

**Comment by TarikViehmann** [comment]
You probably should also add an INSTALL directive for the proto dir

**Review by TarikViehmann — APPROVED** [review]
thank you!

**Pull request merged**
